import { User, Skill, Match } from "./insforge";

export const mockCurrentUser: User = {
  id: "1",
  github_id: "dev1",
  name: "Alex Chen",
  avatar_url: "https://avatars.githubusercontent.com/u/1?v=4",
  bio: "Full-stack developer passionate about React and Node.js. Love building developer tools.",
  location: "Seattle, WA",
  html_url: "https://github.com/alexchen",
};

export const mockCurrentUserSkills: Skill[] = [
  { id: "1", user_id: "1", skill_name: "React", skill_count: 15 },
  { id: "2", user_id: "1", skill_name: "TypeScript", skill_count: 12 },
  { id: "3", user_id: "1", skill_name: "Node.js", skill_count: 10 },
  { id: "4", user_id: "1", skill_name: "Next.js", skill_count: 8 },
];

export const mockMatches: Match[] = [
  {
    userId: "2",
    name: "Sarah Miller",
    avatar: "https://avatars.githubusercontent.com/u/2?v=4",
    skills: ["Go", "TypeScript", "React", "PostgreSQL"],
    matchScore: 78,
    sharedSkills: ["React", "TypeScript"],
    location: "Seattle, WA",
    bio: "Backend engineer with a frontend twist. Building scalable systems at startups.",
    htmlUrl: "https://github.com/sarahmiller",
  },
  {
    userId: "3",
    name: "James Wilson",
    avatar: "https://avatars.githubusercontent.com/u/3?v=4",
    skills: ["Python", "Django", "PostgreSQL", "AWS"],
    matchScore: 65,
    sharedSkills: ["PostgreSQL"],
    location: "Seattle, WA",
    bio: "Python enthusiast and cloud architect. Helping teams scale their infrastructure.",
    htmlUrl: "https://github.com/jameswilson",
  },
  {
    userId: "4",
    name: "Emily Zhang",
    avatar: "https://avatars.githubusercontent.com/u/4?v=4",
    skills: ["React", "TypeScript", "GraphQL", "Node.js"],
    matchScore: 92,
    sharedSkills: ["React", "TypeScript", "Node.js"],
    location: "Remote",
    bio: "Frontend specialist focused on developer experience and design systems.",
    htmlUrl: "https://github.com/emilyzhang",
  },
  {
    userId: "5",
    name: "Michael Park",
    avatar: "https://avatars.githubusercontent.com/u/5?v=4",
    skills: ["Unity", "C#", "AR/VR", "Blender"],
    matchScore: 45,
    sharedSkills: [],
    location: "Seattle, WA",
    bio: "Game developer exploring the metaverse. Always learning new 3D tech.",
    htmlUrl: "https://github.com/michaelpark",
  },
  {
    userId: "6",
    name: "Lisa Johnson",
    avatar: "https://avatars.githubusercontent.com/u/6?v=4",
    skills: ["Vue.js", "TypeScript", "Node.js", "MongoDB"],
    matchScore: 70,
    sharedSkills: ["TypeScript", "Node.js"],
    location: "Portland, OR",
    bio: "Full-stack developer who loves Vue and building community tools.",
    htmlUrl: "https://github.com/lisajohnson",
  },
  {
    userId: "7",
    name: "David Kim",
    avatar: "https://avatars.githubusercontent.com/u/7?v=4",
    skills: ["Rust", "Go", "TypeScript", "WebAssembly"],
    matchScore: 55,
    sharedSkills: ["TypeScript"],
    location: "San Francisco, CA",
    bio: "Systems programmer exploring the boundaries of web performance.",
    htmlUrl: "https://github.com/davidkim",
  },
  {
    userId: "8",
    name: "Rachel Green",
    avatar: "https://avatars.githubusercontent.com/u/8?v=4",
    skills: ["React", "Next.js", "Tailwind", "Prisma"],
    matchScore: 88,
    sharedSkills: ["React", "Next.js"],
    location: "Seattle, WA",
    bio: "Frontend engineer building beautiful, accessible web applications.",
    htmlUrl: "https://github.com/rachelgreen",
  },
  {
    userId: "9",
    name: "Tom Anderson",
    avatar: "https://avatars.githubusercontent.com/u/9?v=4",
    skills: ["Java", "Spring", "PostgreSQL", "Docker"],
    matchScore: 50,
    sharedSkills: ["PostgreSQL"],
    location: "Remote",
    bio: "Backend developer with 10+ years of experience in enterprise systems.",
    htmlUrl: "https://github.com/tomanderson",
  },
];

export const mockUsers: User[] = [
  mockCurrentUser,
  {
    id: "2",
    github_id: "dev2",
    name: "Sarah Miller",
    avatar_url: "https://avatars.githubusercontent.com/u/2?v=4",
    bio: "Backend engineer with a frontend twist. Building scalable systems at startups.",
    location: "Seattle, WA",
    html_url: "https://github.com/sarahmiller",
  },
  {
    id: "3",
    github_id: "dev3",
    name: "James Wilson",
    avatar_url: "https://avatars.githubusercontent.com/u/3?v=4",
    bio: "Python enthusiast and cloud architect. Helping teams scale their infrastructure.",
    location: "Seattle, WA",
    html_url: "https://github.com/jameswilson",
  },
  {
    id: "4",
    github_id: "dev4",
    name: "Emily Zhang",
    avatar_url: "https://avatars.githubusercontent.com/u/4?v=4",
    bio: "Frontend specialist focused on developer experience and design systems.",
    location: "Remote",
    html_url: "https://github.com/emilyzhang",
  },
  {
    id: "5",
    github_id: "dev5",
    name: "Michael Park",
    avatar_url: "https://avatars.githubusercontent.com/u/5?v=4",
    bio: "Game developer exploring the metaverse. Always learning new 3D tech.",
    location: "Seattle, WA",
    html_url: "https://github.com/michaelpark",
  },
  {
    id: "6",
    github_id: "dev6",
    name: "Lisa Johnson",
    avatar_url: "https://avatars.githubusercontent.com/u/6?v=4",
    bio: "Full-stack developer who loves Vue and building community tools.",
    location: "Portland, OR",
    html_url: "https://github.com/lisajohnson",
  },
  {
    id: "7",
    github_id: "dev7",
    name: "David Kim",
    avatar_url: "https://avatars.githubusercontent.com/u/7?v=4",
    bio: "Systems programmer exploring the boundaries of web performance.",
    location: "San Francisco, CA",
    html_url: "https://github.com/davidkim",
  },
  {
    id: "8",
    github_id: "dev8",
    name: "Rachel Green",
    avatar_url: "https://avatars.githubusercontent.com/u/8?v=4",
    bio: "Frontend engineer building beautiful, accessible web applications.",
    location: "Seattle, WA",
    html_url: "https://github.com/rachelgreen",
  },
  {
    id: "9",
    github_id: "dev9",
    name: "Tom Anderson",
    avatar_url: "https://avatars.githubusercontent.com/u/9?v=4",
    bio: "Backend developer with 10+ years of experience in enterprise systems.",
    location: "Remote",
    html_url: "https://github.com/tomanderson",
  },
];
